syntax = "proto3";

package userService;
option java_multiple_files = true;
option java_package="com.restaurant.commons.core.rpc.user";
option java_outer_classname = "UserServiceRpc";

service UserService{
    //Existence checks
    rpc existsByPhoneNumber(ExistsByPhoneNumberRequest) returns (ExistsResponse);
    rpc existsByEmail(ExistsByEmailRequest) returns (ExistsResponse);
}

//Request messages
message ExistsByPhoneNumberRequest {
    string phone_number = 1;
}

message ExistsByEmailRequest {
    string email = 1;
}


//Response messages
message ExistsResponse {
    bool exists = 1;
}

