syntax = "proto3";

package userService;
option java_multiple_files = true;
option java_package="com.restaurant.commons.core.rpc.user";
option java_outer_classname = "UserServiceRpc";

service UserService{
    //Existence checks
    rpc ExistsByPhoneNumber(ExistsByPhoneNumberRequest) returns (ExistsResponse);
    rpc ExistsByEmail(ExistsByEmailRequest) returns (ExistsResponse);
    rpc CreateUser(CreateUserRequest) returns (CreateUserResponse);

    // Lookup
    rpc FindByEmail(FindByEmailRequest) returns (FoundUserResponse);
    rpc FindById(FindByIdRequest) returns (FoundUserResponse);
}

//Request messages
message ExistsByPhoneNumberRequest {
    string phone_number = 1;
}

message ExistsByEmailRequest {
    string email = 1;
}

message CreateUserRequest {
    string email = 1;
    string password = 2;
    string phone_number = 3;
    string first_name = 4;
    string last_name = 5;
    string avatar_url = 6;
}

message FindByEmailRequest {
    string email = 1;
}

message FindByIdRequest {
    string id = 1;
}

//Response messages
message ExistsResponse {
    bool exists = 1;
}

message CreateUserResponse {
    string id = 1;
    string email = 2;
    string first_name = 3;
    string last_name = 4;
    string phone_number = 5;
    bool success = 6;
    string message = 7;
}

message FoundUserResponse {
    string id = 1;
    string email = 2;
    string password = 3;
    string first_name = 4;
    string last_name = 5;
    string avatar_url = 6;
    string user_type = 7;
    bool is_active = 8;
    bool is_verified = 9;
    bool is_deleted = 10;
    bool found = 11;
}